<a href="https://colab.research.google.com/github/Vonewman/Algorithme/blob/master/Python_Numpy_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.95968604 -1.56532186  0.6940435  -0.71929287 -1.90713525]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.95968604 -1.56532186  0.6940435  -0.71929287 -1.90713525]


In [5]:
print(np.dot(a, a.T))

8.007473307428036


In [6]:
a = np.random.randn(5, 1)
print(a)

[[-1.12745992]
 [-0.43179753]
 [ 0.03939446]
 [-0.27984827]
 [-1.02841021]]


In [7]:
print(a.T)

[[-1.12745992 -0.43179753  0.03939446 -0.27984827 -1.02841021]]


In [8]:
print(np.dot(a,a.T))

[[ 1.27116587  0.48683441 -0.04441567  0.31551771  1.1594913 ]
 [ 0.48683441  0.18644911 -0.01701043  0.12083779  0.44406499]
 [-0.04441567 -0.01701043  0.00155192 -0.01102447 -0.04051366]
 [ 0.31551771  0.12083779 -0.01102447  0.07831505  0.28779882]
 [ 1.1594913   0.44406499 -0.04051366  0.28779882  1.05762757]]
